# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [7]:
import numpy as np
arr1d = np.arange(10)
arr2d = arr1d.reshape(2,5)
arr2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [17]:
arr1 = np.arange(10,dtype = np.int8).reshape(2,5)
arr2 = np.ones((2,5),dtype=np.int8)
np.vstack((arr1,arr2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [18]:
np.hstack((arr1,arr2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]], dtype=int8)

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [20]:
arr1.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int8)

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [21]:
arr1 = np.arange(15).reshape(3,5)
arr1.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [24]:
arr = np.arange(15)
arr.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [27]:
arr = np.random.randn(5,5)
print("Array ",arr)
print("Square",np.square(arr))

Array  [[-0.69554874  0.04525537 -0.44415763  0.65707558  0.07561536]
 [-1.95930276 -0.39190764  1.13387739  0.26219506 -1.93146454]
 [ 0.93374096 -1.99153791 -1.63157429  0.38496932 -0.09592398]
 [-0.91668342  0.47670605  0.09383225 -0.88844298  0.09967108]
 [-0.0904012  -0.90652804  0.38805189 -1.20108807 -2.1988638 ]]
Square [[4.83788047e-01 2.04804886e-03 1.97275998e-01 4.31748315e-01
  5.71768216e-03]
 [3.83886731e+00 1.53591596e-01 1.28567793e+00 6.87462492e-02
  3.73055526e+00]
 [8.71872186e-01 3.96622324e+00 2.66203467e+00 1.48201376e-01
  9.20141053e-03]
 [8.40308491e-01 2.27248657e-01 8.80449081e-03 7.89330936e-01
  9.93432480e-03]
 [8.17237701e-03 8.21793081e-01 1.50584268e-01 1.44261254e+00
  4.83500202e+00]]


## Question:8

### Create 5x6 an array and find the mean?

In [29]:
arr = np.random.randn(5,6)
np.mean(arr)

-0.18210716713562367

## Question:9

### Find the standard deviation of the previous array in Q8?

In [30]:
np.std(arr)

0.923928495316144

## Question:10

### Find the median of the previous array in Q8?

In [31]:
np.median(arr)

-0.05145065506777376

## Question:11

### Find the transpose of the previous array in Q8?

In [33]:
np.transpose(arr)

array([[ 0.38729364,  0.36596771, -1.5072092 , -0.18377513, -0.51052424],
       [ 1.39349944, -1.59471946, -0.2883831 , -1.03857156,  1.54331556],
       [ 0.69326464, -1.15612519,  0.09964396, -0.11079317, -0.60120945],
       [-1.6027353 ,  0.39047131,  1.11906898, -0.99155193, -2.05484489],
       [ 0.00789186, -1.49496171,  0.64298728,  0.30899362, -0.71895148],
       [ 0.89401454,  0.22878445,  0.3748049 , -0.24274585,  0.18388475]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [34]:
arr = np.random.randn(4,4)
print(arr)
print("trace = ",np.trace(arr))

[[ 1.39395681  0.38528922  1.00361161 -0.36266592]
 [ 0.35816606 -0.2020445  -0.5312651  -0.19310454]
 [-1.91636102 -0.22194471 -0.44730981  0.60036624]
 [-1.30638233  0.03013016  0.97633666 -0.35324442]]
trace =  0.39135808385002757


## Question:13

### Find the determinant of the previous array in Q12?

In [37]:
np.linalg.det(arr)

0.04328885845765833

## Question:14

### Find the 5th and 95th percentile of an array?

In [39]:
arr = np.random.randn(25)
arr.sort()
arrLen = len(arr)
five_percent = int(5*arrLen/100)
nintyFive_percent = int(95*arrLen/100)
print(arr)
print("5th Percentile ",arr[:five_percent])
print("95th Percentile " ,arr[:nintyFive_percent])

[-1.23844219 -1.12973846 -1.11904759 -0.95029654 -0.89974106 -0.83110109
 -0.81458559 -0.7644876  -0.72944582 -0.41609922 -0.14853378 -0.06373087
 -0.02505493  0.10492083  0.26373494  0.30288191  0.30701993  0.35983794
  0.37421049  0.55950592  0.75779223  0.80325737  0.85747487  1.07279225
  1.57608843]
5th Percentile  [-1.23844219]
95th Percentile  [-1.23844219 -1.12973846 -1.11904759 -0.95029654 -0.89974106 -0.83110109
 -0.81458559 -0.7644876  -0.72944582 -0.41609922 -0.14853378 -0.06373087
 -0.02505493  0.10492083  0.26373494  0.30288191  0.30701993  0.35983794
  0.37421049  0.55950592  0.75779223  0.80325737  0.85747487]


## Question:15

### How to find if a given array has any null values?

* we may caste array as boolean and use 'all' method to find if all of them are True. Then array don't has a null value


In [51]:
arr = np.array([1,2,3,None])
arr

array([1, 2, 3, None], dtype=object)

In [52]:
arr.astype(np.bool).all()

False